import { readdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptRoot, "../..");
const adapter = join(repoRoot, "packages/engine-adapter/src");
const sdk = join(repoRoot, "packages/sdk/src");
const sdkModules = join(sdk, "modules");
const runtimeClient = join(repoRoot, "packages/runtime-client/src");
const generatedDocs = join(repoRoot, "docs/assistant");
const hostAssistant = join(repoRoot, "packages/host/src/assistant");
const domainSource = join(repoRoot, "packages/domain/src");

/** Every non-test `.ts` in `directory` that `matches`, sorted for determinism. */
function sourcesIn(
  directory: string,
  matches: (name: string) => boolean,
): string[] {
  return readdirSync(directory)
    .filter(
      (name) =>
        name.endsWith(".ts") && !name.endsWith(".test.ts") && matches(name),
    )
    .sort()
    .map((name) => join(directory, name));
}

/**
 * Every non-test `.ts` under `directory`, at any depth, in path order.
 *
 * The SDK's module tree is taken WHOLE — no per-file allowlist. Which files
 * hold operations is decided by the code, not by this list: a file whose
 * functions never reach the wire contributes nothing (`no request call`), so a
 * `types.ts` costs a parse and a new module is covered the day it is written.
 * Only tests are excluded, because a fixture is not a surface.
 */
function sourcesUnder(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) =>
      entry.isDirectory()
        ? sourcesUnder(join(directory, entry.name))
        : entry.name.endsWith(".ts") && !entry.name.endsWith(".test.ts")
          ? [join(directory, entry.name)]
          : [],
    )
    .sort();
}

export const assistantPaths = {
  /**
   * The live client surface: the control-plane modules that issue the requests,
   * the cluster mixins the app calls them through, and the whole of the SDK's
   * module tree (the behavior layer every surface binds). `cp/fetch.ts` is not
   * a source — it holds the transport itself — but it is read for the shared
   * path helpers (`agentPath`) the modules build their paths from.
   */
  operationSources: [
    ...sourcesIn(join(adapter, "cp"), (name) => name !== "fetch.ts"),
    ...sourcesIn(join(adapter, "client"), (name) => name.endsWith("-mixin.ts")),
    // LAST on purpose: the SDK implements the writes the mixins delegate to it,
    // and a few reads the control plane also serves. Names collide there, and
    // first source wins — so the control-plane copy stays canonical and the SDK
    // contributes only the operations nothing else implements.
    ...sourcesUnder(sdkModules),
  ],
  /** Whether a source belongs to the SDK's module tree (factory-published). */
  isModuleSource: (path: string): boolean =>
    !relative(sdkModules, path).startsWith(".."),
  transportSource: join(adapter, "cp", "fetch.ts"),
  /**
   * Read to RESOLVE a request, never to publish an operation.
   *
   * `sdk.ts` names the facade property each module factory is mounted at, which
   * is the namespace its operations are dispatched under. The runtime-client
   * sub-clients hold the path literals an SDK module reaches the host through —
   * the second hop of a two-hop request. Both are hashed with the operation
   * sources, so a path moved inside a sub-client is drift like any other.
   */
  facadeSource: join(sdk, "sdk.ts"),
  resolverSources: sourcesIn(runtimeClient, (name) =>
    name.startsWith("client"),
  ),
  biome: join(repoRoot, "node_modules/.bin/biome"),
  repo: repoRoot,
};

/**
 * Where every generated artifact says it came from. ONE sentence, carried by
 * the catalog's `$comment` and by the header of each document beside it: a
 * header naming fewer sources than the generator actually reads is how a
 * reader comes to edit an SDK module and expect nothing downstream to move.
 */
export const ASSISTANT_PROVENANCE =
  "Generated by pnpm gen:assistant-catalog from the live engine adapter (packages/engine-adapter), the SDK's module tree (packages/sdk/src/modules) and the runtime-client sub-clients they reach the host through (packages/runtime-client/src). Do not edit.";

/**
 * Every file one generation writes, with the committed copy's home. The catalog
 * lands in the HOST package because the host imports it as a module: embedded at
 * build time, it travels inside the container bundle and the Bun-compiled
 * desktop sidecar alike, so no artifact has to locate a file it cannot reach.
 * The capability index lands in DOMAIN for the same reason: the runtime folds
 * it into the coordinator's system prompt, so it must be a module both the
 * container bundle and the desktop sidecar carry. The three documents are for
 * people and live under `docs/assistant/`.
 */
export const assistantOutputs = [
  { file: "assistant-catalog.generated.json", directory: hostAssistant },
  { file: "assistant-capability-index.generated.ts", directory: domainSource },
  { file: "assistant-capabilities.md", directory: generatedDocs },
  { file: "assistant-coverage.md", directory: generatedDocs },
  { file: "assistant-operations.md", directory: generatedDocs },
] as const;

/** A source path as it reads in the generated header — repo-relative, POSIX. */
export function repoRelative(path: string): string {
  return relative(repoRoot, path).split(/[\\/]/).join("/");
}
