/** Generated curated concept tags. Name words are added by the matcher. */
import type { SidebarGroupGlyphName } from "./sidebar-group-glyphs";

export const SIDEBAR_GROUP_GLYPH_TAGS = {
  bank: ["money", "finance", "accounting", "payment", "banking", "business"],
  "bar-chart": [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  "bar-graph": [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  briefcase: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
  ],
  calculator: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
  ],
  cart: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
  ],
  chart: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  dashboard: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  "dollar-bill": [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
  ],
  dollar: ["money", "finance", "accounting", "payment", "banking", "business"],
  euro: ["money", "finance", "accounting", "payment", "banking", "business"],
  europe: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
  ],
  "money-stack": ["finance", "accounting", "payment", "banking", "business"],
  "pie-chart": [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  project: ["money", "finance", "accounting", "payment", "banking", "business"],
  rank: ["money", "finance", "accounting", "payment", "banking", "business"],
  report: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  shop: ["money", "finance", "accounting", "payment", "banking", "business"],
  spreadsheet: [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  "text-paragraph": [
    "money",
    "finance",
    "accounting",
    "payment",
    "banking",
    "business",
    "documents",
    "writing",
    "notes",
    "content",
    "knowledge",
    "charts",
    "data",
    "analytics",
    "metrics",
    "insights",
  ],
  accessibility: ["people", "team", "community", "collaboration", "identity"],
  anonymous: [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  "car-pool": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
  ],
  conversation: ["people", "team", "community", "collaboration", "identity"],
  "face-flat-smile": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
  ],
  "face-heart-eyes": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "communication",
    "message",
    "contact",
    "social",
    "support",
    "health",
    "medical",
    "wellness",
    "care",
    "science",
  ],
  face: ["people", "team", "community", "collaboration", "identity"],
  "face-id": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  "face-mask": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "health",
    "medical",
    "wellness",
    "care",
    "science",
  ],
  "face-monocle": ["people", "team", "community", "collaboration", "identity"],
  "face-star-eyes": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
  ],
  "face-sunglasses": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "nature",
    "outdoors",
    "environment",
    "weather",
  ],
  "face-surprise": ["people", "team", "community", "collaboration", "identity"],
  "face-tired": ["people", "team", "community", "collaboration", "identity"],
  "face-tongue": ["people", "team", "community", "collaboration", "identity"],
  heart: [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "communication",
    "message",
    "contact",
    "social",
    "support",
    "health",
    "medical",
    "wellness",
    "care",
    "science",
  ],
  "locker-room": [
    "people",
    "team",
    "community",
    "collaboration",
    "identity",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  shrug: ["people", "team", "community", "collaboration", "identity"],
  subgroup: ["people", "team", "community", "collaboration", "identity"],
  "tee-shirt": ["people", "team", "community", "collaboration", "identity"],
  "thumbs-down": ["people", "team", "community", "collaboration", "identity"],
  "thumbs-up": ["people", "team", "community", "collaboration", "identity"],
  "unhappy-face": ["people", "team", "community", "collaboration", "identity"],
  union: ["people", "team", "community", "collaboration", "identity"],
  users: ["people", "team", "community", "collaboration", "identity"],
  chat: ["communication", "message", "contact", "social", "support"],
  "chat-line": ["communication", "message", "contact", "social", "support"],
  email: [
    "communication",
    "message",
    "contact",
    "social",
    "support",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  hear: [
    "communication",
    "message",
    "contact",
    "social",
    "support",
    "health",
    "medical",
    "wellness",
    "care",
    "science",
  ],
  megaphone: ["communication", "message", "contact", "social", "support"],
  mic: ["communication", "message", "contact", "social", "support"],
  "mobile-phone": [
    "communication",
    "message",
    "contact",
    "social",
    "support",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  notified: ["communication", "message", "contact", "social", "support"],
  phone: ["communication", "message", "contact", "social", "support"],
  "question-mark": ["communication", "message", "contact", "social", "support"],
  "resolved-chat": ["communication", "message", "contact", "social", "support"],
  resolved: ["communication", "message", "contact", "social", "support"],
  sound: ["communication", "message", "contact", "social", "support"],
  speaker: ["communication", "message", "contact", "social", "support"],
  subscribe: ["communication", "message", "contact", "social", "support"],
  "air-tag": [
    "time",
    "schedule",
    "deadline",
    "planning",
    "calendar",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  "alarm-clock": [
    "time",
    "schedule",
    "deadline",
    "planning",
    "calendar",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  alarm: ["time", "schedule", "deadline", "planning", "calendar"],
  clock: [
    "time",
    "schedule",
    "deadline",
    "planning",
    "calendar",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  "clock-outline": [
    "time",
    "schedule",
    "deadline",
    "planning",
    "calendar",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  hourglass: ["time", "schedule", "deadline", "planning", "calendar"],
  stopwatch: ["time", "schedule", "deadline", "planning", "calendar"],
  watch: ["time", "schedule", "deadline", "planning", "calendar"],
  africa: ["travel", "transport", "vehicle", "journey", "logistics"],
  airplane: [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  "american-foot-ball": [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
  ],
  anchor: ["travel", "transport", "vehicle", "journey", "logistics"],
  asia: ["travel", "transport", "vehicle", "journey", "logistics"],
  astronaut: [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "ai",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  australia: ["travel", "transport", "vehicle", "journey", "logistics"],
  bike: ["travel", "transport", "vehicle", "journey", "logistics"],
  binocular: ["travel", "transport", "vehicle", "journey", "logistics"],
  bus: ["travel", "transport", "vehicle", "journey", "logistics"],
  car: ["travel", "transport", "vehicle", "journey", "logistics"],
  compass: ["travel", "transport", "vehicle", "journey", "logistics"],
  "design-tools": [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "building",
    "construction",
    "maintenance",
    "work",
  ],
  direction: ["travel", "transport", "vehicle", "journey", "logistics"],
  flag: ["travel", "transport", "vehicle", "journey", "logistics"],
  garage: [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "home",
    "place",
    "facilities",
    "operations",
  ],
  "military-truck": ["travel", "transport", "vehicle", "journey", "logistics"],
  "moving-staircase": [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  "north-america": ["travel", "transport", "vehicle", "journey", "logistics"],
  pin: ["travel", "transport", "vehicle", "journey", "logistics"],
  "ping-pong": [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "sports",
    "games",
    "fitness",
    "recreation",
    "competition",
  ],
  "poker-card": [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "sports",
    "games",
    "fitness",
    "recreation",
    "competition",
  ],
  rocket: [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "ai",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  routing: ["travel", "transport", "vehicle", "journey", "logistics"],
  ship: ["travel", "transport", "vehicle", "journey", "logistics"],
  sign: ["travel", "transport", "vehicle", "journey", "logistics"],
  signature: [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "documents",
    "writing",
    "notes",
    "content",
    "knowledge",
  ],
  "south-america": ["travel", "transport", "vehicle", "journey", "logistics"],
  taxi: ["travel", "transport", "vehicle", "journey", "logistics"],
  "traffic-light": ["travel", "transport", "vehicle", "journey", "logistics"],
  train: [
    "travel",
    "transport",
    "vehicle",
    "journey",
    "logistics",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  tram: ["travel", "transport", "vehicle", "journey", "logistics"],
  world: ["travel", "transport", "vehicle", "journey", "logistics"],
  basket: ["food", "meal", "restaurant", "kitchen"],
  basketball: [
    "food",
    "meal",
    "restaurant",
    "kitchen",
    "sports",
    "games",
    "fitness",
    "recreation",
    "competition",
  ],
  burger: ["food", "meal", "restaurant", "kitchen"],
  coffee: ["food", "meal", "restaurant", "kitchen"],
  biscuit: ["food", "meal", "restaurant", "kitchen"],
  pizza: ["food", "meal", "restaurant", "kitchen"],
  ramen: ["food", "meal", "restaurant", "kitchen"],
  bandage: ["health", "medical", "wellness", "care", "science"],
  bones: ["health", "medical", "wellness", "care", "science"],
  brain: [
    "health",
    "medical",
    "wellness",
    "care",
    "science",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "ai",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  chemist: ["health", "medical", "wellness", "care", "science"],
  cross: ["health", "medical", "wellness", "care", "science"],
  dna: ["health", "medical", "wellness", "care", "science"],
  dumbbell: [
    "health",
    "medical",
    "wellness",
    "care",
    "science",
    "sports",
    "games",
    "fitness",
    "recreation",
    "competition",
  ],
  "foot-print": ["health", "medical", "wellness", "care", "science"],
  health: ["medical", "wellness", "care", "science"],
  mask: ["health", "medical", "wellness", "care", "science"],
  pills: ["health", "medical", "wellness", "care", "science"],
  "safety-kit": [
    "health",
    "medical",
    "wellness",
    "care",
    "science",
    "security",
    "privacy",
    "protection",
    "access",
  ],
  "desktop-window": [
    "nature",
    "outdoors",
    "environment",
    "weather",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  dino: ["nature", "outdoors", "environment", "weather"],
  feather: ["nature", "outdoors", "environment", "weather"],
  fire: ["nature", "outdoors", "environment", "weather"],
  flower: ["nature", "outdoors", "environment", "weather"],
  leaf: ["nature", "outdoors", "environment", "weather"],
  moon: ["nature", "outdoors", "environment", "weather"],
  mountain: [
    "nature",
    "outdoors",
    "environment",
    "weather",
    "tech",
    "devices",
    "software",
    "development",
    "computing",
  ],
  "palm-tree": ["nature", "outdoors", "environment", "weather"],
  recycle: ["nature", "outdoors", "environment", "weather"],
  storm: ["nature", "outdoors", "environment", "weather"],
  sun: ["nature", "outdoors", "environment", "weather"],
  surfer: ["nature", "outdoors", "environment", "weather"],
  tree: ["nature", "outdoors", "environment", "weather"],
  umbrella: ["nature", "outdoors", "environment", "weather"],
  "wind-turbine": ["nature", "outdoors", "environment", "weather"],
  "ai-document": [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "documents",
    "writing",
    "notes",
    "content",
    "knowledge",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  ai: [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  "ai-writing": [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "documents",
    "notes",
    "content",
    "knowledge",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  automation: [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "ai",
    "intelligence",
    "assistant",
    "future",
  ],
  battery: ["tech", "devices", "software", "development", "computing"],
  bolt: ["tech", "devices", "software", "development", "computing"],
  bug: ["tech", "devices", "software", "development", "computing"],
  "camera-ai": [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "intelligence",
    "automation",
    "assistant",
    "future",
    "creative",
    "design",
    "art",
    "media",
    "ideas",
  ],
  chip: ["tech", "devices", "software", "development", "computing"],
  "click-button": ["tech", "devices", "software", "development", "computing"],
  cloud: ["tech", "devices", "software", "development", "computing"],
  computer: ["tech", "devices", "software", "development", "computing"],
  connected: ["tech", "devices", "software", "development", "computing"],
  cube: ["tech", "devices", "software", "development", "computing"],
  database: ["tech", "devices", "software", "development", "computing"],
  "electric-plug": ["tech", "devices", "software", "development", "computing"],
  hack: [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  modem: ["tech", "devices", "software", "development", "computing"],
  network: ["tech", "devices", "software", "development", "computing"],
  paint: [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "tools",
    "building",
    "construction",
    "maintenance",
    "work",
    "creative",
    "design",
    "art",
    "media",
    "ideas",
  ],
  pointer: ["tech", "devices", "software", "development", "computing"],
  robot: [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "ai",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  search: ["tech", "devices", "software", "development", "computing"],
  server: ["tech", "devices", "software", "development", "computing"],
  tablet: ["tech", "devices", "software", "development", "computing"],
  terminal: ["tech", "devices", "software", "development", "computing"],
  "writing-ai": [
    "tech",
    "devices",
    "software",
    "development",
    "computing",
    "documents",
    "notes",
    "content",
    "knowledge",
    "intelligence",
    "automation",
    "assistant",
    "future",
  ],
  book: ["documents", "writing", "notes", "content", "knowledge"],
  "book-open": ["documents", "writing", "notes", "content", "knowledge"],
  bookmark: ["documents", "writing", "notes", "content", "knowledge"],
  education: ["documents", "writing", "notes", "content", "knowledge"],
  "floppy-disk": ["documents", "writing", "notes", "content", "knowledge"],
  image: [
    "documents",
    "writing",
    "notes",
    "content",
    "knowledge",
    "creative",
    "design",
    "art",
    "media",
    "ideas",
  ],
  "note-pad": ["documents", "writing", "notes", "content", "knowledge"],
  page: ["documents", "writing", "notes", "content", "knowledge"],
  policy: [
    "documents",
    "writing",
    "notes",
    "content",
    "knowledge",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  "text-block": [
    "documents",
    "writing",
    "notes",
    "content",
    "knowledge",
    "security",
    "privacy",
    "protection",
    "access",
    "safety",
  ],
  write: ["documents", "writing", "notes", "content", "knowledge"],
  diagram: ["charts", "data", "analytics", "metrics", "insights"],
  process: ["charts", "data", "analytics", "metrics", "insights"],
  radar: ["charts", "data", "analytics", "metrics", "insights"],
  "scatter-plot": ["charts", "data", "analytics", "metrics", "insights"],
  speedometer: ["charts", "data", "analytics", "metrics", "insights"],
  "bowling-ball": ["sports", "games", "fitness", "recreation", "competition"],
  dice: ["sports", "games", "fitness", "recreation", "competition"],
  golf: ["sports", "games", "fitness", "recreation", "competition"],
  jersey: ["sports", "games", "fitness", "recreation", "competition"],
  joystick: ["sports", "games", "fitness", "recreation", "competition"],
  runner: ["sports", "games", "fitness", "recreation", "competition"],
  "soccer-ball": ["sports", "games", "fitness", "recreation", "competition"],
  stadium: ["sports", "games", "fitness", "recreation", "competition"],
  "tennis-ball": ["sports", "games", "fitness", "recreation", "competition"],
  brick: ["tools", "building", "construction", "maintenance", "work"],
  brush: [
    "tools",
    "building",
    "construction",
    "maintenance",
    "work",
    "creative",
    "design",
    "art",
    "media",
    "ideas",
  ],
  bucket: ["tools", "building", "construction", "maintenance", "work"],
  cone: ["tools", "building", "construction", "maintenance", "work"],
  "construction-barrier": ["tools", "building", "maintenance", "work"],
  crane: ["tools", "building", "construction", "maintenance", "work"],
  eraser: ["tools", "building", "construction", "maintenance", "work"],
  extinguisher: ["tools", "building", "construction", "maintenance", "work"],
  factory: [
    "tools",
    "building",
    "construction",
    "maintenance",
    "work",
    "home",
    "place",
    "facilities",
    "operations",
  ],
  flashlight: ["tools", "building", "construction", "maintenance", "work"],
  gears: ["tools", "building", "construction", "maintenance", "work"],
  ladder: ["tools", "building", "construction", "maintenance", "work"],
  magnet: ["tools", "building", "construction", "maintenance", "work"],
  scissors: ["tools", "building", "construction", "maintenance", "work"],
  trash: ["tools", "building", "construction", "maintenance", "work"],
  wall: [
    "tools",
    "building",
    "construction",
    "maintenance",
    "work",
    "home",
    "place",
    "facilities",
    "operations",
  ],
  wrench: ["tools", "building", "construction", "maintenance", "work"],
  alert: ["security", "privacy", "protection", "access", "safety"],
  judge: ["security", "privacy", "protection", "access", "safety"],
  shield: ["security", "privacy", "protection", "access", "safety"],
  skull: ["security", "privacy", "protection", "access", "safety"],
  "small-lock": ["security", "privacy", "protection", "access", "safety"],
  "crystal-ball": [
    "ai",
    "intelligence",
    "automation",
    "assistant",
    "future",
    "creative",
    "design",
    "art",
    "media",
    "ideas",
  ],
  "magic-wand": [
    "ai",
    "intelligence",
    "automation",
    "assistant",
    "future",
    "creative",
    "design",
    "art",
    "media",
    "ideas",
  ],
  asterisk: ["creative", "design", "art", "media", "ideas"],
  camera: ["creative", "design", "art", "media", "ideas"],
  circle: ["creative", "design", "art", "media", "ideas"],
  "empty-circle": ["creative", "design", "art", "media", "ideas"],
  "exclamation-mark": ["creative", "design", "art", "media", "ideas"],
  "light-bulb": ["creative", "design", "art", "media", "ideas"],
  "music-key": ["creative", "design", "art", "media", "ideas"],
  "music-tape": ["creative", "design", "art", "media", "ideas"],
  starred: ["creative", "design", "art", "media", "ideas"],
  video: ["creative", "design", "art", "media", "ideas"],
  "view-finder": ["creative", "design", "art", "media", "ideas"],
  bed: ["home", "place", "facilities", "operations"],
  boombox: ["home", "place", "facilities", "operations"],
  box: ["home", "place", "facilities", "operations"],
  "box-open": ["home", "place", "facilities", "operations"],
  "cloth-hanger": ["home", "place", "facilities", "operations"],
  crown: ["home", "place", "facilities", "operations"],
  home: ["place", "facilities", "operations"],
  present: ["home", "place", "facilities", "operations"],
  spaces: ["home", "place", "facilities", "operations"],
  tower: ["home", "place", "facilities", "operations"],
} satisfies Record<SidebarGroupGlyphName, readonly string[]>;
